
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Christopher Lawrence
 */
public class inputstudentenroll extends javax.swing.JInternalFrame {

    /**
     * Creates new form inputstudentenroll
     */
    public inputstudentenroll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel s_name = new javax.swing.JLabel();
        s_name_text = new javax.swing.JTextField();
        javax.swing.JLabel s_number = new javax.swing.JLabel();
        s_number_int = new javax.swing.JTextField();
        javax.swing.JLabel y_level = new javax.swing.JLabel();
        y_level_text = new javax.swing.JTextField();
        javax.swing.JLabel dept = new javax.swing.JLabel();
        dept_text = new javax.swing.JTextField();
        javax.swing.JButton save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        studentlist = new javax.swing.JTable();

        setBackground(new java.awt.Color(185, 228, 229));

        jPanel1.setBackground(new java.awt.Color(187, 231, 232));

        s_name.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        s_name.setText("Student Name:");

        s_name_text.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        s_name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_name_textActionPerformed(evt);
            }
        });

        s_number.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        s_number.setText("Student Number:");

        s_number_int.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        s_number_int.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_number_intActionPerformed(evt);
            }
        });

        y_level.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        y_level.setText("Year Level: ");

        y_level_text.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        y_level_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y_level_textActionPerformed(evt);
            }
        });

        dept.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        dept.setText("Department:");

        dept_text.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        dept_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept_textActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(157, 195, 249));
        save.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(157, 195, 249));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        studentlist.setBackground(new java.awt.Color(185, 228, 229));
        studentlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Student Number", "Year Level", "Department"
            }
        ));
        studentlist.setGridColor(new java.awt.Color(157, 195, 249));
        studentlist.setSelectionBackground(new java.awt.Color(157, 195, 249));
        jScrollPane1.setViewportView(studentlist);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s_name, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_number, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y_level, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(y_level_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addComponent(s_number_int, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dept_text, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(s_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s_name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s_number_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(y_level)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(y_level_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dept_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_name_textActionPerformed

    }//GEN-LAST:event_s_name_textActionPerformed

    private void s_number_intActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_number_intActionPerformed

    }//GEN-LAST:event_s_number_intActionPerformed

    private void y_level_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y_level_textActionPerformed

    }//GEN-LAST:event_y_level_textActionPerformed

    private void dept_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept_textActionPerformed

    }//GEN-LAST:event_dept_textActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String student_name = s_name_text.getText();
        String student_number = s_number_int.getText();
        String year_level = y_level_text.getText();
        String department = dept_text.getText();

        try{
            if(student_name.isEmpty() || student_number.isEmpty() || year_level.isEmpty() || department.isEmpty()){
                JOptionPane.showMessageDialog(this,
                    "Please Enter all the fields",
                    "Try again",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                DefaultTableModel tblModel = (DefaultTableModel)studentlist.getModel();
                tblModel.addRow(new Object[] {student_name, student_number, year_level, department});

                s_name_text.setText("");
                s_number_int.setText("");
                y_level_text.setText("");
                dept_text.setText("");
            }

            FileWriter writer = new FileWriter("C:\\Users\\Christopher Lawrence\\Documents\\GitHub\\GES_project/enrolledstudentinput.txt", true);
            writer.write(""+student_name+", "+student_number+", "+year_level+", "+department+"");
            writer.write(System.getProperty("line.seperator"));
            writer.close();
            JOptionPane.showMessageDialog(null, "Success");
            setVisible(false);
            new inputstudentenroll().setVisible(true);
        } catch(Exception e){
        }

    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = studentlist.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this,
                "No row is selected! Please select one row",
                "Select row",
                JOptionPane.ERROR_MESSAGE
            );
        } else {
            DefaultTableModel model = (DefaultTableModel)studentlist.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dept_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField s_name_text;
    private javax.swing.JTextField s_number_int;
    private javax.swing.JTable studentlist;
    private javax.swing.JTextField y_level_text;
    // End of variables declaration//GEN-END:variables
}
