/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enroll_student = new javax.swing.JButton();
        grade_encoding = new javax.swing.JButton();
        student_grade = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        FacName = new javax.swing.JLabel();
        main_desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");

        jPanel1.setBackground(new java.awt.Color(185, 230, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enroll_student.setBackground(new java.awt.Color(204, 204, 255));
        enroll_student.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        enroll_student.setText("Enrolled Students");
        enroll_student.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enroll_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enroll_studentActionPerformed(evt);
            }
        });
        jPanel1.add(enroll_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, -1));

        grade_encoding.setBackground(new java.awt.Color(204, 204, 255));
        grade_encoding.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        grade_encoding.setText("Grade Encoding");
        grade_encoding.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grade_encoding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grade_encodingActionPerformed(evt);
            }
        });
        jPanel1.add(grade_encoding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, -1));

        student_grade.setBackground(new java.awt.Color(204, 204, 255));
        student_grade.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        student_grade.setText("Student Grade");
        student_grade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        student_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_gradeActionPerformed(evt);
            }
        });
        jPanel1.add(student_grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, -1));

        profile.setBackground(new java.awt.Color(204, 204, 255));
        profile.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        profile.setText("My Profile");
        profile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, -1));

        log_out.setBackground(new java.awt.Color(204, 204, 255));
        log_out.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        log_out.setText("LOG OUT");
        log_out.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        jPanel1.add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SIDE.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 692));

        jPanel3.setBackground(new java.awt.Color(155, 193, 250));

        FacName.setFont(new java.awt.Font("MS PGothic", 0, 18)); // NOI18N
        FacName.setText("Faculty:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(FacName, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 496, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(FacName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 890, 50));

        javax.swing.GroupLayout main_desktopLayout = new javax.swing.GroupLayout(main_desktop);
        main_desktop.setLayout(main_desktopLayout);
        main_desktopLayout.setHorizontalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        main_desktopLayout.setVerticalGroup(
            main_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel1.add(main_desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 890, 660));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileActionPerformed

    private void student_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_gradeActionPerformed

    private void grade_encodingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grade_encodingActionPerformed
       
    }//GEN-LAST:event_grade_encodingActionPerformed

    private void enroll_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enroll_studentActionPerformed
        main_desktop.removeAll();
        inputstudentenroll enrollstudentI = new inputstudentenroll();
        main_desktop.add(enrollstudentI).setVisible(true);
    }//GEN-LAST:event_enroll_studentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FacName;
    private javax.swing.JButton enroll_student;
    private javax.swing.JButton grade_encoding;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton log_out;
    private javax.swing.JDesktopPane main_desktop;
    private javax.swing.JButton profile;
    private javax.swing.JButton student_grade;
    // End of variables declaration//GEN-END:variables
}
